variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -Icpprb -pthread"
  CC: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -Icpprb -pthread"
  GIT_SUBMODULE_STRATEGY: recursive
  COVERAGE_RCFILE: .coveragerc

stages:
  - page_export
  - build_image
  - build
  - test
  - page_build
  - test
  - test_coverage
  - page_deploy
  - upload

.job_template: &setup
  image: &dev_image $CI_REGISTRY_IMAGE/build:latest
  before_script:
    - g++ --version
    - python3 --version
  except:
    - schedules

.test_template: &py_setup
  image: *dev_image
  stage: test
  before_script:
    - g++ --version
    - python3 --version
    - pip3 install -e .['all']
  except:
    - schedules
  artifacts:
    paths:
      - .coverage.*

docker_build:
  image: docker:latest
  stage: build_image
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/build:latest || true
    - docker build --pull=true --cache-from $CI_REGISTRY_IMAGE/build:latest -t $CI_REGISTRY_IMAGE/build:latest .
    - docker run $CI_REGISTRY_IMAGE/build:latest
    - docker push $CI_REGISTRY_IMAGE/build:latest
  only:
    - schedules

cpprb_build:
  <<: *setup
  stage: build
  script:
    - python3 setup.py build_ext --inplace --force --define CYTHON_TRACE_NOGIL
  artifacts:
    paths:
      - cpprb/*.html
      - cpprb/*.cpp
      - '*.so'

ReplayBuffer.cpp:
  <<: *setup
  stage: test
  script:
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer

SegmentTree.cpp:
  <<: *setup
  stage: test
  script:
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree

ReplayBuffer:
  <<: *py_setup
  script:
    - coverage run test/PyReplayBuffer.py

issue:
  <<: *py_setup
  script:
    - coverage run test/issue.py

multi_rew:
  <<: *py_setup
  script:
    - coverage run test/multi_rew.py

gym:
  <<: *py_setup
  script:
    - coverage run test/gym.py

high_level_api:
  <<: *py_setup
  script:
    - coverage run test/HighLevelAPI.py

features:
  <<: *py_setup
  script:
    - coverage run test/features.py

v8:
  <<: *py_setup
  script:
    - coverage run test/v8.py

coverage:
  <<: *setup
  stage: test_coverage
  script:
    - coverage combine
    - coverage report
    - coverage html -d public/coverage
  artifacts:
    paths:
      - public
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

emacs:
  image: iquiw/alpine-emacs
  stage: page_export
  script:
    - emacs --batch README.org -l site/init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
    - emacs --batch README.org --eval '(org-md-export-to-markdown)'
    - cd site
    - emacs --batch site.org -l init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
  artifacts:
    paths:
      - site/content
      - README.md
  only:
    - master
  except:
    - schedules

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: page_deploy
  environment: production
  script:
    - hugo version
    - cd site
    - hugo -c content -v
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - schedules

sphinx:
  image: *dev_image
  stage: page_build
  environment: production
  script:
    - sphinx-apidoc -F -M -o sphinx cpprb
    - sphinx-build -b html sphinx public/api
  artifacts:
    paths:
      - sphinx/*.rst
      - public
  only:
    - master
  except:
    - schedules

annotation:
  image: *dev_image
  stage: page_build
  environment: production
  script:
    - mkdir -p public/annotation
    - mv cpprb/*.html public/annotation/
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - schedules

pypi:
  image: *dev_image
  stage: upload
  environment: production
  script:
    - rm -rf cpprb/*.cpp
    - python3 setup.py clean
    - python3 setup.py build_ext sdist
    - twine upload dist/*.tar.gz
  only:
    - tags
  except:
    - branches
    - schedules

repo:
  image: docker:latest
  stage: upload
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/build:latest
    - docker tag $CI_REGISTRY_IMAGE/build:latest $CI_REGISTRY_IMAGE/build:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE/build:$CI_COMMIT_TAG
  only:
    - tags
  except:
    - branches
    - schedules

RingIndex:
  <<: *setup
  stage: test
  script:
    - $CXX -S -o design_study/RingIndex.s design_study/RingIndex.cc
    - $CXX -o design_study/RingIndex design_study/RingIndex.cc
    - design_study/RingIndex
  when: manual
  artifacts:
    paths:
      - design_study/*.s
