name: CI

on: [push]

jobs:
  readme:
    container: iquiw/alpine-emacs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: emacs --batch README.org --eval '(org-md-export-to-markdown)'
      - uses: actions/upload-artifact@v1
        with:
          name: README
          path: README.md
  build:
    needs: readme
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8']
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: pip install cython setuptools
      - run: pip install '.[gym]' gym
      - run: python -m unittest discover . '*.py'
        working-directory: './test'
      - run: pip install wheel twine
      - uses: actions/download-artifact@v1
        with:
          name: README
      - run: mv README/README.md README.md
      - run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - run: python -m twine upload -u __token__ -p ${{ secrets.pypi_password }} --skip-existing dist/cpprb-*
        if: github.event_name == 'push' && startsWith(github.event.ref,'refs/tags/v')
        continue-on-error: true
