name: Design Study

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - working-directory: './design_study'
        run: |
          g++ -std=c++17 -O3 -I../cpprb -Wall -Wextra -o RingIndex RingIndex.cc
          ./RingIndex
